### ISSUE TITLE
Non-minified Version?

### ISSUE THREAD

**Issue by Abion47** [atamocius/flutterstein-3d#3]
This is insanely cool. I was wondering if you were planning on releasing a non-minified/obfuscated-by-circumstance version of the code? (There's enough wizardry going on in there that I'm sure it would be hard enough to follow what's going on without having to guess at class, method, and variable names. :P)

**Comment by atamocius** [comment]
The branch [`prior-to-reduction`](https://github.com/atamocius/flutterstein-3d/tree/prior-to-reduction) is the one you are looking for.

I minified the code by hand so it is quite a number of commits behind master but it is essentially the same as the final minified form.
